version: '3.8'

services:
  bank-backend:
    container_name: bank-backend
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"