spring.application.name=bank-backend
spring.data.mongodb.uri=mongodb://localhost:27017/bankSystem

ai.api.key=AIzaSyD7Pt6Sx6cJecKeixwP_VI74oto37tFxWw
server.port=${PORT:8081}
mongodb+srv:mongodb+srv://SamirChaudhary:Apple%40123@samirchaudhary.m6sfesp.mongodb.net/bankSystem